export const NETWORKS_REQUEST: "NETWORKS_REQUEST" = "NETWORKS_REQUEST";
export const NETWORKS_ERROR: "NETWORKS_ERROR" = "NETWORKS_ERROR";
export const NETWORKS_SUCCESS: "NETWORKS_SUCCESS" = "NETWORKS_SUCCESS";
export const NETWORKS_SETACTIVE: "NETWORKS_SETACTIVE" = "NETWORKS_SETACTIVE";