export const STATIONS_REQUEST: "STATIONS_REQUEST" = "STATIONS_REQUEST";
export const STATIONS_ERROR: "STATIONS_ERROR" = "STATIONS_ERROR";
export const STATIONS_SUCCESS: "STATIONS_SUCCESS" = "STATIONS_SUCCESS";